#!/usr/bin/env bash
# script to install and setup nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx restart
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
