#!/usr/bin/env bash
# script to install and setup nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx startus 
echo "Hello World!" | sudo tee > /var/www/html/index.nginx-debian.html
